# Paso 1 
Importamos pandas como pd y de igual forma importamos nuestra vase de datos y definirémos a df como nuestra base de datos

In [3]:
import pandas as pd 
pd.read_csv("https://raw.githubusercontent.com/vida092/diplomado_big_data/refs/heads/main/peliculas.csv")
df = pd.read_csv("https://raw.githubusercontent.com/vida092/diplomado_big_data/refs/heads/main/peliculas.csv")

# Paso 2
Contestarémos las siguientes 3 preguntas
* ¿Cuántas películas hay en el dataset?
* ¿Cuántas variables o columnas contiene el dataset?
* ¿Cuáles son las columnas que contiene el DataFrame?

In [5]:
df.shape
# Aqui podemos ver que hay 100 peliculas en el dataset y 12 columnas

(100, 12)

In [ ]:
df.columns
# En este vemos cuales son las columnas de nuestro df

Index(['id', 'titulo', 'fecha_estreno', 'genero', 'duracion_min',
       'presupuesto_musd', 'taquilla_musd', 'popularidad', 'rating', 'votos',
       'idioma_original', 'adulto'],
      dtype='str')

# Para hacer más sencilla la resolución de las siguientes preguntas las agruparé de 3 en 3.
* ¿Qué tipo de dato tiene cada columna?
* ¿Existen valores faltantes en el dataset?
* ¿Cuánta información contiene cada columna?

In [ ]:
df.dtypes
# Gracias a este código podemos ver que tipo de dato tiene cada columna

id                    int64
titulo                  str
fecha_estreno           str
genero                  str
duracion_min          int64
presupuesto_musd    float64
taquilla_musd       float64
popularidad         float64
rating              float64
votos                 int64
idioma_original         str
adulto                 bool
dtype: object

In [ ]:
df.info()
#Con este código verémos si existen valores faltantes en nuestro DataFrame, también nos dice cuanta info tiene cada columna

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                100 non-null    int64
 1   titulo            100 non-null    str
 2   fecha_estreno     100 non-null    str
 3   genero            100 non-null    str
 4   duracion_min      100 non-null    int64
 5   presupuesto_musd  100 non-null    float64
 6   taquilla_musd     100 non-null    float64
 7   popularidad       100 non-null    float64
 8   rating            100 non-null    float64
 9   votos             100 non-null    int64
 10  idioma_original   100 non-null    str
 11  adulto            100 non-null    bool
dtypes: bool(1), float64(4), int64(3), str(4)
memory usage: 8.8 KB

### Para estas preguntas también podemos recurrir al _df.info_
* ¿Qué columnas contienen información numérica?

la respuesta está en ver en que columnas aparece el _dtype_ "int64" o float64 las cuales son: 0,4,5,6,7,8 y 9

* ¿Qué columnas contienen información categórica o textual?

Aqui los que responden la pregunta son las columnas cuyo _Dtype_ es "str" y "bool" : 1,2,3,10 y 11

# Para las siguientes preguntas:
* Obtén únicamente la columna que contiene el título de las películas.
* Obtén únicamente la columna que contiene el rating de las películas.
* Obtén únicamente las columnas correspondientes al título, género y rating.

Usarémos el siguiente codigo : _df[["titulo","rating","genero"]]_

In [9]:
df[["titulo","rating","genero"]]

               titulo  rating           genero
0           100 Years     0.0       Sin género
1     American Static     0.0  Ciencia ficción
2           September     0.0           Terror
3         Light Years     0.0       Sin género
4             Harvest     0.0           Terror
..                ...     ...              ...
95    Batman: Parte 2     0.0         Misterio
96            Золушка     0.0       Sin género
97       Heart Eyes 2     0.0           Terror
98  Murder, She Wrote     0.0         Misterio
99     Endless Summer     0.0            Drama

[100 rows x 3 columns]

# * Obtén las estadísticas descriptivas de las variables numéricas.

In [11]:
df.describe()

,id,duracion_min,presupuesto_musd,taquilla_musd,popularidad,rating,votos
count,1.000000e+02,100.000000,100.0000,100.0,100.000000,100.0,100.0
mean,1.479390e+06,21.730000,8.1805,0.0,1.385000,0.0,0.0
std,3.080932e+05,50.850316,29.3839,0.0,2.069646,0.0,0.0
min,2.165270e+05,0.000000,0.0000,0.0,0.010000,0.0,0.0
25%,1.363082e+06,0.000000,0.0000,0.0,0.320000,0.0,0.0
50%,1.582366e+06,0.000000,0.0000,0.0,0.640000,0.0,0.0
75%,1.712100e+06,0.000000,0.0000,0.0,1.645000,0.0,0.0
max,1.752779e+06,186.000000,190.0000,0.0,14.950000,0.0,0.0

### Como las siguiente preguntas se tratan de acciones que usan  _.mean_ para promedios o _.max_ para maximos, las agrupé:
* ¿Cuál es el rating promedio de las películas?
* ¿Cuál es la duración promedio de las películas?
* ¿Cuál es la película con mayor duración?
* ¿Cuál es la película con mayor rating?
* ¿Cuál es la película que recibió más votos?

In [ ]:
df["rating"].mean()
# Promedio deL Rating

np.float64(0.0)

In [ ]:
df["duracion_min"].mean()
# Promedio de la duración

np.float64(21.73)

In [18]:
df["duracion_min"].max()
# Pelicula con la duracion maxima

np.int64(186)

In [20]:
#Otra vez la pelicula con la mayor duración pero más bonito
Peli_Larga = df["duracion_min"] == 186
df[Peli_Larga]

,id,titulo,fecha_estreno,genero,duracion_min,presupuesto_musd,taquilla_musd,popularidad,rating,votos,idioma_original,adulto
1,1742644,American Static,2047-05-11,Ciencia ficción,186,0.0,0.0,0.24,0.0,0,en,False

#### Pelicula con mayor Rating no existe pq todas tienen 0, al parecer pasa lo mismo con los votos

In [21]:
# Pelicula con más votos
df["votos"].max()

np.int64(0)

In [22]:
df[df["votos"]==0]

,id,titulo,fecha_estreno,genero,duracion_min,presupuesto_musd,taquilla_musd,popularidad,rating,votos,idioma_original,adulto
0,1711051,100 Years,2099-12-31,Sin género,0,0.0,0.0,0.26,0.0,0,en,False
1,1742644,American Static,2047-05-11,Ciencia ficción,186,0.0,0.0,0.24,0.0,0,en,False
2,1742657,September,2045-07-08,Terror,140,0.0,0.0,0.25,0.0,0,en,False
3,1370697,Light Years,2044-10-01,Sin género,7,0.0,0.0,0.69,0.0,0,en,False
4,1742658,Harvest,2043-10-03,Terror,184,0.0,0.0,0.21,0.0,0,en,False
...,...,...,...,...,...,...,...,...,...,...,...,...
95,806704,Batman: Parte 2,2028-02-17,Misterio,0,0.0,0.0,5.52,0.0,0,en,False
96,1662286,Золушка,2028-02-10,Sin género,0,0.0,0.0,0.94,0.0,0,ru,False
97,1625381,Heart Eyes 2,2028-02-10,Terror,0,0.0,0.0,0.51,0.0,0,en,False
98,1188748,"Murder, She Wrote",2028-02-03,Misterio,0,0.0,0.0,0.63,0.0,0,en,False
99,1634592,Endless Summer,2028-01-28,Drama,130,0.0,0.0,1.61,0.0,0,en,False

## Van las últimas preguntas
* ¿Qué géneros aparecen en el dataset y cuántas películas hay de cada género?
* ¿Qué idioma aparece con mayor frecuencia?

In [ ]:
df["genero"].value_counts()
# Este código enlista los valores de la columna género y sus repeticiones

genero
Drama              16
Terror             15
Animación          14
Sin género         12
Acción              9
Ciencia ficción     6
Crimen              6
Fantasía            5
Aventura            4
Documental          2
Comedia             2
Familia             2
Suspense            2
Misterio            2
Bélica              1
Romance             1
Historia            1
Name: count, dtype: int64

In [ ]:
df["idioma_original"].value_counts()
# observamos que el idioms más frecuente es el inglés (en)

idioma_original
en    78
ru     7
fr     3
pt     2
hi     2
es     1
tr     1
kn     1
cs     1
it     1
ko     1
pl     1
nl     1
Name: count, dtype: int64